{
 "title": "Final_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request_Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sample_app_requests_created", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App_Request_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sample_app_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory_Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU_Process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}